version: 2.1
workflows:
  build-workflow:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - upload:
          requires:
            - build
      - cleanup:
          requires:
            - upload
jobs:
  setup:
    machine: true
    resource_class: ponces/docker
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            cd build
            docker build -t aosp .
            docker stop aosp && docker rm aosp || true
            docker run --name aosp -d -it aosp /bin/bash
            docker exec -it aosp /bin/sh -c "git clone https://github.com/ponces/treble_aosp"
  build:
    machine: true
    resource_class: ponces/docker
    steps:
      - run:
          no_output_timeout: 1h
          name: Build ROM
          command: docker exec -it aosp /bin/sh -c "bash treble_aosp/build.sh"
  upload:
    machine: true
    resource_class: ponces/docker
    environment:
      GITHUB_API_TOKEN: $GITHUB_API_TOKEN
    steps:
      - run:
          name: Upload to GitHub
          command: docker exec -it aosp /bin/sh -c "bash treble_aosp/upload.sh"
  cleanup:
    machine: true
    resource_class: ponces/docker
    steps:
      - run:
          name: Cleanup
          command: docker stop aosp && docker rm aosp
